import type { Metadata } from 'next'
import './globals.css'
import PageLoader from '@/components/layout/PageLoader'
import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import JsonLd from '@/components/seo/JsonLd'
import { orgSchema, websiteSchema } from '@/lib/seo'

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://zolarux.com.ng'

export const metadata: Metadata = {
  title: {
    default: 'Zolarux | Trusted Gadget Seller — Phones, Laptops & Accessories',
    template: '%s | Zolarux',
  },
  description:
    'Buy phones, laptops and accessories from a verified seller with a 5-year track record. You get exactly what you ordered — or your money back. No arguments.',
  keywords: [
    'buy phones Nigeria',
    'buy laptops Nigeria',
    'trusted gadget seller Nigeria',
    'buy iPhone Nigeria',
    'gadget seller guarantee',
    'Zolarux',
    'buy gadgets online Nigeria',
    'UK used phones Nigeria',
  ],
  metadataBase: new URL(BASE_URL),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    type: 'website',
    locale: 'en_NG',
    siteName: 'Zolarux',
    title: 'Zolarux | Trusted Gadget Seller — Phones, Laptops & Accessories',
    description: '5 years. 100+ customers. Nobody has ever lost money buying from me. Phones, laptops, and accessories — guaranteed or refunded.',
    url: BASE_URL,
    // Open Graph image is generated by app/opengraph-image.tsx (1200×630)
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Zolarux | Trusted Gadget Seller — Phones, Laptops & Accessories',
    description: '5 years. 100+ customers. Nobody has ever lost money buying from me. Phones, laptops, and accessories — guaranteed or refunded.',
    // Twitter image is generated by app/twitter-image.tsx (1200×630)
  },
  icons: {
    icon: '/icon.png',
    apple: '/apple-icon.png',
  },
  robots: { index: true, follow: true },
  // Uncomment and add your Bing Webmaster Tools verification code:
  // verification: { other: { 'msvalidate.01': 'YOUR_BING_VERIFICATION_CODE' } },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `try{var t=localStorage.getItem('zlx_theme');var d=t==='dark'||(t!=='light'&&window.matchMedia('(prefers-color-scheme: dark)').matches);if(d)document.documentElement.classList.add('dark')}catch(e){}`,
          }}
        />
      </head>
      <body className="antialiased bg-white text-gray-900 dark:bg-gray-950 dark:text-gray-100">
        <JsonLd data={[orgSchema(), websiteSchema()]} />
        <PageLoader />
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}

